console.log(0 + '1');
console.log(0 - '1');
console.log(0 * '1');
console.log(0 / '1');
console.log(undefined || 1);
console.log(undefined && 1);
console.log(undefined ?? 1);
console.log(0 ?? 1);
console.log(Number.isNaN(+' 0001 '));
console.log(Number.isNaN(+' 0001_'));
console.log(+' 0001 ' === NaN);
console.log(null === undefined);
console.log(null === null);
console.log(undefined == undefined);
console.log(undefined === undefined);
console.log({} === {});
console.log({ a: 1 } === { a: 1 });
console.log({ a: 1 } == { a: 1 });
